%% Optimisation_Interface — Wing Structures outputs for Role 7

% ── Primary optimisation metrics ─────────────────────────────────────
m_wing      = WS.m_wing_total;    % kg  Class II.5 Al — primary MDO value
m_frac_MTOM = WS.m_frac_MTOM;    % —   fraction of MTOM

% ── Fidelity ladder for uncertainty analysis ──────────────────────────
m_raymer    = WS.m_raymer;        % kg  Class I  upper bound
m_torenbeek = WS.m_torenbeek;    % kg  Class I  best fit for this class
m_usaf      = WS.m_usaf;         % kg  Class I  lower bound
m_I_II      = WS.m_ClassI_II_Al; % kg  3-method average

% ── Sensitivity study outputs (from SensitivityStudy.m) ──────────────
%  Plots are generated by StructuresAll.m.
%  For programmatic access, re-run SensitivityStudy with parameter sweep.

% ── Stiffness summary for aeroelastic constraint ─────────────────────
GJ_over_EI  = WS.GJ_over_EI;     % —   < 0.2 = aileron reversal risk

fprintf('\n--- Wing Structures → Optimisation handoff ---\n');
fprintf('  Wing mass (Class II.5, Al)   %8.0f kg  (%.2f%% MTOM)\n', m_wing, m_frac_MTOM*100);
fprintf('  Fidelity spread:\n');
fprintf('    Raymer      %8.0f kg\n', m_raymer);
fprintf('    Torenbeek   %8.0f kg\n', m_torenbeek);
fprintf('    USAF        %8.0f kg\n', m_usaf);
fprintf('    I/II avg    %8.0f kg\n', m_I_II);
fprintf('    II.5        %8.0f kg  ← MDO value\n', m_wing);
fprintf('  GJ/EI at root              %8.4f\n', GJ_over_EI);
