function [] = construct_avl(obj,Mach,Alt,Aerofoil)
%CONSTRUCT_AVL 
% For constructing an AVL file to be run

if nargin < 2
    Mach = 0;
    Alt = 11000; % Guess at cruise alt [m]
end

fid = fopen('unconventional.avl','w');   % open file for writing

fprintf(fid,[ ...
'Plane Unconventional\n',...
'#Mach\n',...
'%f\n',...
'#IYsym   IZsym   Zsym\n',...
'0 0 0.0\n',...
'#Sref    Cref    Bref\n',...
'%f %f %f\n',...
'#Xref    Yref    Zref\n',...
'%f %f %f\n',...
'#\n',...
'#\n',...
'#====================================================================\n',...
'SURFACE\n',...
'Wing\n',...
'#Nchordwise  Cspace   Nspanwise   Sspace\n',...
'25            1.0       30         1.0\n',...
'#\n',...
'YDUPLICATE\n',...
'0.0\n',...
'#\n',...
'TRANSLATE\n',...
'%f 0.0 0.0\n',...
'ANGLE\n',...
'%f\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',... % Wing root
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'0.0    0.0    %f     %f     %f   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'flap     1.0   %f    0.0 0.0 0.0   1.0\n',...
'CONTROL\n',...
'aileron  -1.0   %f    0.0 0.0 0.0  -1.0\n',...
'CLAF\n',...
'1.0\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',... % Wing wing kink
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'%f     %f    %f     %f     %f   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'flap     1.0   %f    0.0 0.0 0.0   1.0\n',...
'CONTROL\n',...
'aileron  -1.0   %f    0.0 0.0 0.0  -1.0\n',...
'CLAF\n',...
'1.0\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',... % Wing tip
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'%f     %f    %f     %f     %f   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'flap     1.0   %f    0.0 0.0 0.0   1.0\n',...
'CONTROL\n',...
'aileron  -1.0   %f    0.0 0.0 0.0  -1.0\n',...
'CLAF\n',...
'1.0\n',...
'#====================================================================\n',...
'SURFACE\n',...
'H-stab\n',...
'#Nchordwise  Cspace   Nspanwise   Sspace\n',...
'10           1.0      15           1.0\n',...
'#\n',...
'YDUPLICATE\n',...
'0.0\n',...
'#\n',...
'TRANSLATE\n',...
'%f 0.0 0.0\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',...
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'0.0     0.0    0.0     %f     %f   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'elevator 1.0    %f     0.0 1.0 0.0  1.0\n',...
'CLAF\n',...
'1.0\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',...
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'%f    %f   %f     %f    %f   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'elevator 1.0    %f     0.0 1.0 0.0  1.0\n',...
'CLAF\n',...
'1.0\n',...
'#====================================================================\n',...
'SURFACE\n',...
'V-stab\n',...
'#Nchordwise  Cspace    Nspanwise  Sspace\n',...
'15            1.0       10          1.0\n',...
'#\n',...
'TRANSLATE\n',...
'%f 0.0 0.0\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',...
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'0.0     0.     0.0     %f     0.0   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'rudder   1.0    %f     0.0 0.0 1.0  1.0\n',...
'CLAF\n',...
'1.0\n',...
'#-------------------------------------------------------------\n',...
'SECTION\n',...
'#Xle    Yle    Zle     Chord   Ainc  Nspanwise  Sspace\n',...
'%f    0.0     %f     %f    0.0   0          0\n',...
'AFILE\n',...
'%s\n',...
'#Cname   Cgain  Xhinge  HingeVec     SgnDup\n',...
'CONTROL\n',...
'rudder   1.0    %f     0.0 0.0 1.0  1.0\n',...
'CLAF\n',...
'1.0\n',...
'#-------------------------------------------------------------\n'], ...
Mach, ...
obj.WingArea, obj.CMAC, obj.WingSpan, ...
0.0, 0.0, 0.0, ...
obj.WingStart,...
0.0, ...% obj.AOA_incident-Wing incidence
obj.WingHeight, obj.RootChord,obj.AOA_incident, ... % Wing SECTION 1 (root)
Aerofoil, ...
obj.FlapStart, obj.AileronStart, ...
obj.Kinkx, obj.Kinky, obj.Kinkz, obj.KinkChord,obj.AOA_incident, ...% Wing SECTION 2 (mid)
Aerofoil, ...
obj.FlapStart, obj.AileronStart, ...
obj.Tipx, obj.WingSpan/2, obj.Tipz, obj.TipChord,obj.AOA_incident, ... % Wing SECTION 3 (tip)
Aerofoil, ...
obj.FlapStart, obj.AileronStart, ... % Horizontal tail translate
obj.HStabStart, ...
obj.HRootChord,obj.AOA_incident, ...% H-tail root section
obj.HorAerofoil, ...
obj.ElevatorHinge, ...
obj.HTipx,obj.HalfTailSpan,obj.HTipz, obj.HTipChord,obj.AOA_incident, ...% H-tail tip section
obj.HorAerofoil, ...
obj.ElevatorHinge, ...
obj.VStabStart, ... % Vertical tail translate
obj.VRootChord,...
obj.VerAerofoil, ... % V-tail root section
obj.RudderHinge, ...
obj.VTipX, obj.VTailSpan, obj.VTipChord, ...% V-tail tip section
obj.VerAerofoil, ...% V-tail tip section
obj.RudderHinge);


fclose(fid);   % always close the file

end