function W = RaymerSection15Weights(p)
% Raymer Section 15 Component Weight Equations
% ALL INPUTS MUST BE IN IMPERIAL UNITS
% Outputs are in pounds (lb)

%% ---------------------------
% PROPULSION GROUP
%% ---------------------------

% (15.31) Nacelle Group
W.nacelle = 0.6724 * p.K_ng * ...
            p.N_Lt^0.10 * ...
            p.N_w^0.294 * ...
            p.N_z^0.119 * ...
            p.W_ec^0.611 * ...
            p.N_en^0.984 * ...
            p.S_n^0.224;

% (15.32) Engine Controls
W.engine_controls = 5.0 * p.N_en + 0.80 * p.L_ec;

% (15.33) Pneumatic Starter
W.starter = 49.19 * ((p.N_en * p.W_en) / 1000)^0.541;

%% ---------------------------
% FUEL & FLIGHT CONTROLS
%% ---------------------------

% (15.34) Fuel System
W.fuel_system = 2.405 * ...
                p.V_t^0.606 * ...
                (1 + p.V_i / p.V_t)^(-1.0) * ...
                (1 + p.V_p / p.V_t) * ...
                p.N_t^0.5;

% (15.35) Flight Controls
W.flight_controls = 145.9 * ...
                    p.N_f^0.554 * ...
                    (1 + p.N_m / p.N_f)^(-1.0) * ...
                    p.S_cs^0.20 * ...
                    (p.I_yaw * 1e-6)^0.07;

%% ---------------------------
% APU & INSTRUMENTS
%% ---------------------------

% (15.36) Installed APU
W.APU_installed = 2.2 * p.W_APU_uninstalled;

% (15.37) Instruments
W.instruments = 4.509 * ...
                p.K_r * ...
                p.K_tp * ...
                p.N_c^0.541 * ...
                p.N_en * ...
                (p.L_f + p.B_w)^0.5;

%% ---------------------------
% HYDRAULICS & ELECTRICAL
%% ---------------------------

% (15.38) Hydraulics
W.hydraulics = 0.2673 * ...
               p.N_f * ...
               (p.L_f + p.B_w)^0.937;

% (15.39) Electrical
W.electrical = 7.291 * ...
               p.R_kva^0.782 * ...
               p.L_a^0.346 * ...
               p.N_gen^0.10;

%% ---------------------------
% AVIONICS
%% ---------------------------

% (15.40) Avionics
W.avionics = 1.73 * p.W_uav^0.983;

%% ---------------------------
% FURNISHINGS
%% ---------------------------

W.W_cargo_system = 0.04 * Payload;

%% ---------------------------
% ENVIRONMENTAL CONTROL
%% ---------------------------

% (15.42) Air Conditioning
W.air_conditioning = 62.36 * ...
                     p.N_p^0.25 * ...
                     (p.V_pr / 1000)^0.604 * ...
                     p.W_uav^0.10;

%% ---------------------------
% ANTI-ICE
%% ---------------------------

% (15.43) Anti-Ice
W.anti_ice = 0.002 * p.W_dg;

%% ---------------------------
% TOTAL SYSTEMS WEIGHT
%% ---------------------------

W.total = W.nacelle + ...
          W.engine_controls + ...
          W.starter + ...
          W.fuel_system + ...
          W.flight_controls + ...
          W.APU_installed + ...
          W.instruments + ...
          W.hydraulics + ...
          W.electrical + ...
          W.avionics + ...
          W.furnishings + ...
          W.air_conditioning + ...
          W.anti_ice;

end